- name: software | docker | install package
  tags: docker, packages
  package:
    name: docker
    state: latest
  notify: "{{ item }}"
  loop:
    - service | docker | start
    - group | docker | create
    - group | docker | add user
# - name: Flush handlers
#   meta: flush_handlers
