# Docker container platform
- name: software | docker | install
  tags:
    - docker
    - packages
  package:
    name: docker
    state: latest
  notify: "{{ item }}"
  loop:
    - service | docker | start
    - group | docker | create
    - group | docker | add user
# - name: Flush handlers
#   meta: flush_handlers
