- name: software | oh-my-zsh | install
  tags:
    - zsh
    - oh-my-zsh
    - packages
  become_user: "{{ user }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  # notify: software | powerlevel10k | install
  notify: config | zsh | login shell
