- name: software | prometheus-node-exporter | install package
  tags: prometheus-node-exporter, packages
  package:
    name: prometheus-node-exporter
    state: latest
  notify: service | prometheus-node-exporter | start
