- name: software | stow | install package
  tags: stow, packages
  package:
    name: stow
    state: latest
  notify: "{{ item }}"
  loop:
    - dotfiles | set

- name: Flush handlers
  meta: flush_handlers