- name: config | multilib | enable
  tags: config, multilib
  replace:
    path: "/etc/pacman.conf"
    regexp: '#\[multilib]\n#Include = \/etc\/pacman.d\/mirrorlist'
    replace: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

