---
#--------------Dev packages-------------------
- import_tasks: software/dev/zsh.yml
- import_tasks: software/dev/bash-completion.yml
- import_tasks: software/dev/bat.yml
- import_tasks: software/dev/git.yml
- import_tasks: software/dev/kitty.yml
- import_tasks: software/dev/vim.yml
- import_tasks: software/dev/ssh.yml
- import_tasks: software/dev/taskwarrior.yml
- import_tasks: software/dev/yazi.yml
- import_tasks: software/dev/docker.yml
- import_tasks: software/dev/docker-c.yml
- import_tasks: software/dev/lsd.yml
- import_tasks: software/dev/oh-my-zsh.yml
- import_tasks: software/dev/lazygit.yml
- import_tasks: software/dev/tmux.yml
- import_tasks: software/dev/neovim.yml
- import_tasks: software/dev/xclip.yml
- import_tasks: software/dev/curlie.yml
- import_tasks: software/dev/uv.yml
- import_tasks: software/dev/devops.yml
- import_tasks: software/dev/tree.yml
- import_tasks: software/dev/npm.yml
- import_tasks: software/dev/zoxide.yml

#--------------System packages----------------
- import_tasks: software/system/bashtop.yml
- import_tasks: software/system/unzip.yml
- import_tasks: software/system/wireplumber.yml
- import_tasks: software/system/pavucontrol.yml
- import_tasks: software/system/fonts.yml
- import_tasks: software/system/ripgrep.yml
- import_tasks: software/system/rsync.yml
- import_tasks: software/system/fzf.yml
- import_tasks: software/system/7zip.yml
- import_tasks: software/system/flatpak.yml
- import_tasks: software/system/ufw.yml
- import_tasks: software/network/network-tools.yml

#--------------Multimedia packages------------
# - import_tasks: software/multimedia/flameshot.yml
- import_tasks: software/multimedia/mpv.yml
- import_tasks: software/multimedia/qbittorrent.yml

#--------------Gaming-------------------------
- import_tasks: software/gaming/steam.yml
# import_tasks: software/gaming/protonup-qt.yml
- import_tasks: software/gaming/gamemode.yml

- import_tasks: desktop_env/niri/main.yml

#--------------Dotfiles-----------------------
- import_tasks: software/dev/stow.yml  

#--------------Others packages/configs--------
- import_tasks: software/system/themes.yml
- import_tasks: software/system/bluetooth.yml 

