- name: desktop | kde-plasma | install packages
  tags: desktop, kde-plasma
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - plasma
    - dolphin
  notify:
    - service | sddm | set
