# 1️⃣ Instala pacotes
- name: desktop env | niri
  tags:
    - desktop
    - niri
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - wlsunset
    - wpa_supplicant
    - thunar
    - evince
    - ly

# 2️⃣ Remove SDDM
- name: Desativar SDDM se estiver habilitado
  tags: ly
  become: true
  shell: |
    if systemctl is-enabled --quiet sddm 2>/dev/null; then
      systemctl disable sddm
    fi

- name: Remover pacote SDDM se existir
  tags: ly
  become: true
  shell: |
    if pacman -Qs sddm > /dev/null; then
      pacman -Rns --noconfirm sddm
    fi

# 3️⃣ Ativa Ly
- name: Habilitar Ly no tty1 e desabilitar getty
  tags: ly
  become: true
  shell: |
    systemctl enable ly@tty1.service
    systemctl disable getty@tty1.service