- name: drivers | bluetooth | install
  tags: drivers, bluetooth
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - bluez
    - bluez-utils
    - bluetui
  notify: service | bluetooth | enable
