- name: software | dnsmasq | install
  tags:
    - packages
    - dnsmasq
  package:
    name: dnsmasq
    state: latest
  notify: "{{ item }}"
  loop:
    - config | dnsmasq | cache
    - service | dnsmasq | start
