# Intel graphics drivers
- name: drivers | intel-gfx | install
  tags:
    - drivers
    - intel-gfx
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - mesa
    - vulkan-intel
    - intel-media-driver
    - lib32-mesa
    - lib32-vulkan-intel
