- name: software | ufw | install
  tags:
    - packages
    - ufw
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - ufw
    - gufw
  notify:
    - service | ufw | enable
    - service | ufw | start
