- name: software | wireplumber | install package
  tags: packages, wireplumber
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - pipewire
    - wireplumber
    - pipewire-pulse
    - pipewire-audio
