- name: config | bspwm | permission
  tags:
    - config
    - bspwm
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - "{{ home }}/.config/bspwm/bspwmrc"
    - "{{ home }}/.config/polybar/launch.sh"
    - "{{ home }}/.config/polybar/scripts/updates.sh"

- name: config | qt5ct | theme
  tags:
    - config
    - qt5ct
  lineinfile:
    path: "/etc/environment"
    line: 'QT_QPA_PLATFORMTHEME="qt5ct"'
