- name: config | autostart | desktop file
  tags: config, autostart
  lineinfile:
    path: "{{ home }}/.config/autostart/modmap.desktop"
    regexp: "^Exec"
    line: "Exec={{ home }}/.scripts/modmap.sh"

- name: config | git | setup
  tags: config, git
  lineinfile:
    path: "{{ home }}/.gitconfig"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^name", line: "name = {{ git_username }}" }
    - { regexp: "^email", line: "email = {{ git_email }}" }

- name: config | window title | shortcut
  tags: config, window title
  lineinfile:
    path: "{{ home }}/.config/dconf/settings.dconf"
    regexp: "^command='bash'"
    line: "command='bash {{ home }}/.scripts/toggle-window-title.sh'"

- name: ssh | github | create key pair
  tags: ssh, github
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
