- name: service | gdm | enable
  tags:
    - service
    - gdm
  service:
    name: gdm
    enabled: yes

- name: desktop | gnome | pacman indicator
  tags:
    - gnome
    - packages
  become_user: '{{ user }}'
  shell:
    cmd: yay -S gnome-shell-extension-arch-update --noconfirm

- name: desktop | gnome | extensions install
  tags:
    - gnome
    - packages
  become_user: '{{ user }}'
  shell:
    cmd: yay -S gnome-shell-extension-blur-my-shell bibata-cursor-theme gnome-shell-extension-clipboard-history --noconfirm

- name: desktop | gnome | extensions enable
  tags:
    - gnome
    - extensions
  become_user: '{{ user }}'
  shell: 'gnome-extensions enable {{ item }}'
  loop:
    - appindicatorsupport@rgcjonas.gmail.com
    - blur-my-shell@aunetx
    - arch-update@RaphaelRochet
    - clipboard-history@alexsaveau.dev

- name: desktop | gnome | shortcuts
  tags:
    - gnome
    - shortcuts
  become_user: '{{ user }}'
  shell:
    cmd: 'dconf load / < {{ home }}/.config/dconf/settings.dconf'

- name: desktop | gnome | extension-manager
  tags:
    - gnome
    - packages
  become_user: "{{ user }}"
  shell:
    cmd: yay -S extension-manager --noconfirm
