- name: service | gdm | enable
  tags: service, gdm
  service:
    name: gdm
    enabled: yes

- name: gnome | pacman update indicator | install
  tags: gnome, packages
  become_user: '{{ user }}'
  shell:
    cmd: yay -S gnome-shell-extension-arch-update --noconfirm

- name: gnome | extensions | install
  tags: gnome, packages
  become_user: '{{ user }}'
  shell:
    cmd: yay -S gnome-shell-extension-blur-my-shell bibata-cursor-theme gnome-shell-extension-clipboard-history --noconfirm

- name: gnome | extensions | enable
  tags: gnome, extensions
  become_user: '{{ user }}'
  shell: 'gnome-extensions enable {{ item }}'
  loop:
    - appindicatorsupport@rgcjonas.gmail.com
    - blur-my-shell@aunetx
    - arch-update@RaphaelRochet
    - clipboard-history@alexsaveau.dev

- name: gnome | shortcuts | set
  tags: gnome, shortcuts
  become_user: '{{ user }}'
  shell:
    cmd: 'dconf load / < {{ home }}/.config/dconf/settings.dconf'

- name: config | mangohud | output
  tags: config, mangohud
  lineinfile:
    path: '{{ home }}/.config/MangoHud/MangoHud.conf'
    regexp: '^output_folder='
    line: 'output_folder={{ home }}'


- name: gnome | extension-manager | install
  tags: gnome, packages
  become_user: "{{ user }}"
  shell:
    cmd: yay -S extension-manager --noconfirm
