# Main handlers file - imports all other handler files
- import_tasks: config.yml
- import_tasks: zsh.yml
- import_tasks: steam.yml
- import_tasks: docker.yml
- import_tasks: tailscale.yml
- import_tasks: locales.yml
- import_tasks: stow.yml
- import_tasks: ufw.yml
- import_tasks: bluetooth.yml
