- name: dotfiles | set
  tags:
    - dotfiles
  become_user: "{{ user }}"
  shell: sh -c "cd ; git clone https://github.com/fabioalmeida08/.dotfiles ; cd .dotfiles ; stow -R --adopt -t ~ */ ; git restore . ; cd niri/.config/niri ; cp config.kdl config.kdl.bak"
