# Wallpaper management handlers
- name: config | wallpapers | create dir
  tags:
    - wallpapers
  file:
    path: "/usr/share/wallpapers"
    state: directory
    mode: "0755"

- name: config | wallpapers | unzip
  tags:
    - wallpapers
  unarchive:
    src: "wallpapers.tar.gz"
    dest: "/usr/share/wallpapers"
    mode: "0744"

# - name: config | wallpapers | create dir
#   file:
#     path: "{{ home }}/Wallpapers"
#     state: directory
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: "0764"
#
# - name: config | wallpapers | unzip
#   unarchive:
#     src: "wallpapers.tar.gz"
#     dest: "{{ home }}/Wallpapers"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: "0764"
#     extra_opts: --strip-components=1

- name: config | wallpapers | create user dir
  tags:
    - wallpapers
  file:
    path: "{{ home }}/Wallpapers"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0764"

- name: config | wallpapers | unzip to user home
  tags:
    - wallpapers
  unarchive:
    src: "wallpapers.tar.gz"
    dest: "{{ home }}/Wallpapers"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0764"
    extra_opts:
      - --strip-components=1
