- name: desktop | gnome | install
  tags:
    - desktop
    - gnome
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - evince
    - gdm
    - gnome-backgrounds
    - gnome-calculator
    - gnome-color-manager
    - gnome-disk-utility
    - gnome-logs
    - gnome-menus
    - gnome-session
    - gnome-settings-daemon
    - gnome-shell
    - gnome-shell-extensions
    - gnome-shell-extension-appindicator
    - gnome-system-monitor
    - gnome-control-center
    - gnome-tweaks
    - gvfs-google
    - gvfs-nfs
    - gvfs-smb
    - xdg-user-dirs
    - baobab
    - nautilus
  notify:
    - config | qt5ct | theme
    - service | gdm | enable
    - desktop | gnome | pacman indicator
    - config | xdg | create
    - desktop | gnome | extension-manager
    - config | wallpapers | create dir
    - config | wallpapers | unzip
    - desktop | gnome | shortcuts
