- name: desktop | xfce | install
  tags:
    - desktop
    - xfce
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - xfce4
    - xfce4-goodies
    - xdg-utils
    - xdg-user-dirs
    - wireless_tools
    - wpa_supplicant
    - gvfs
    - lightdm-gtk-greeter
    - xdotool
    - redshift
  notify:
    - service | lightdm | enable
    - config | xdg | create
    - config | lightdm | greeter
    - config | lightdm | gtk greeter
    - config | wallpapers | extract
    - dotfiles | xfce4 | set
